version: '3.8'
services:
  server:
    build:
        context: .
        dockerfile: dockerfiles/nginx.dockerfile
    ports:
        - '8000:80'
    volumes:
      - ./backend_api:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./backend_api:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
